---
title: "prolifico pilot"
author: "Nick Spyrison"
date: "11/01/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
require(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
rel_path <- function(rel_path){
  rel_dir  <- dirname(rstudioapi::getSourceEditorContext()$path)
  rel_path <- paste0(rel_dir, "/", rel_path)
  normalizePath(rel_path)
}

## Read from gsheets API4 and save local
if(F){
    ss_id <- "1K9qkMVRkrNO0vufofQJKWIJUyTys_8uVtEBdJBL_DzU" ## hash id of the google sheet
    raw <- googlesheets4::read_sheet(ss_id, sheet = 1L)
    raw$full_perm_num <- unlist(raw$full_perm_num)
    v <- rep(NULL, nrow(raw))
    raw$prolific_id <- unlist(as.character(raw$prolific_id))
    #str(raw)
    saveRDS(raw, rel_path("data/raw_prolific_pilot.rds"))
}
## Load load and clean, save cleaned
if(F){
    raw <- readRDS(rel_path("data/raw_prolific_pilot.rds"))
    ## Filter to only task data including training
    dat_active <- raw[raw$plot_active == TRUE, ] %>% 
        filter(!is.na(key))
    ## Pivot variable coulmns longer
    source(rel_path("../../paper/R/pivot_longer_resp_ans_tbl.r"))
    dat_longer <- pivot_longer_resp_ans_tbl(dat = dat_active)
    ## Aggregate to task grain.
    dat_task_agg <- aggregate_task_vars(dat_longer)
    saveRDS(dat_task_agg, rel_path("data/dat_task_agg_prolific_pilot.rds"))
}
## load aggregated data.
dat_task_agg <- readRDS(rel_path("data/dat_task_agg_prolific_pilot.rds"))

```

## Marks by factor, marks by period

```{r}
(marks_by_fct <- 
     ggplot(dat_task_agg, aes(x = factor, y = task_marks, 
                              color = is_training, fill = is_training)) + 
     geom_boxplot(position = "dodge", alpha = .5) +
     geom_jitter(width = .2, height = .05) + 
     labs(title = "Marks by factor") + theme_minimal() + 
     scale_color_brewer(palette = "Dark2") + scale_fill_brewer(palette = "Dark2") +
     geom_hline(yintercept = 0))

(marks_by_eval <-
    ggplot(dat_task_agg, aes(x = eval, y = task_marks, color = is_training, fill = is_training)) + 
    geom_boxplot(position = "dodge", alpha = .5) +
    geom_jitter(width = .2, height = .05) + 
    labs(title = "Marks by order of evaluatin") + theme_minimal() + 
    scale_color_brewer(palette = "Dark2") + scale_fill_brewer(palette = "Dark2") +
    geom_hline(yintercept = 0))

(speed_by_factor <-
        ggplot(dat_task_agg, aes(x = factor, y = max_sec_on_pg, 
                                 color = is_training, fill = is_training)) + 
        geom_boxplot(position = "dodge", alpha = .5) +
        geom_jitter(width = .2, height = .05) +
        labs(title = "Seconds till last response by factor") + theme_minimal() +
        scale_color_brewer(palette = "Dark2") + scale_fill_brewer(palette = "Dark2"))

(speed_by_eval <-
        ggplot(dat_task_agg, aes(x = factor, y = max_sec_on_pg,
                                 color = is_training, fill = is_training)) + 
        geom_boxplot(position = "dodge", alpha = .5) +
        geom_jitter(width = .2, height = .05) +
        labs(title = "Seconds till last response by evaluation order") + theme_minimal() +
        scale_color_brewer(palette = "Dark2") + scale_fill_brewer(palette = "Dark2"))

##TODO: XXX ___CONTINUE HERE____

```

## Input and Response interactions

```{r}
(input_interactions <- 
     ggplot(dat_task_agg, aes(x = factor, y = task_input_inter,
                              color = is_training, fill = is_training)) + 
     geom_boxplot(position = "dodge", alpha = .5) +
     geom_jitter(width = .2, height = .05) +
     labs(title = "Number of input interaction by factor (throughness)") +
     theme_minimal() + 
     scale_color_brewer(palette = "Dark2") +
     scale_fill_brewer(palette = "Dark2"))

(response_interactions <-
        ggplot(dat_task_agg, aes(x = factor, y = task_resp_inter,
                                 color = is_training, fill = is_training)) +
        geom_boxplot(position = "dodge", alpha = .5) +
        geom_jitter(width = .2, height = .05) +
        labs(title = "Number of response interaction by factor (~ inverse of confidence)") +
        theme_minimal() + 
        scale_color_brewer(palette = "Dark2") +
        scale_fill_brewer(palette = "Dark2"))
```

