---
title: "animated pdf example"
author: "Nick Spyrison"
date: "5/10/2021"
output:
  #html_document:
  pdf_document:
  #bookdown::pdf_document2:
    toc: true
header-includes: 
  - \usepackage{animate}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE
)
```

Keep an eye on YAML header and chunk options.

# pacman example

```{r pacmanExample, animation.hook='gifski', fig.show='animate', interval=1/4}
for (i in 1:3) {
  pie(c(i %% 3, 6), col = c('red', 'yellow'), labels = NA)
}
```

# tourr -- only 2 frames
```{r Tourr, animation.hook='gifski', fig.show='animate', interval=1/4}
require(tourr)
if(interactive() == T)
  ?save_history

t1 <- save_history(flea[, 1:6], max = 4)
animate_xy(flea[, 1:6], planned_tour(t1))
message("why only 2 frames!?")
```

# gganimate 
```{r gganimate, fig.show='animate', interval=.2}
require(gganimate)
message("doesn't seem applly `interval` and spacing from gganimate as well.")

ggplot(airquality, aes(Day, Temp, group = Month)) +
  geom_line() +
  transition_reveal(Month)
```


# spinifex render_gganimate 
```{r spinifex, fig.show='animate', interval=.2}
require(spinifex)
message("only works with an implicit call, but not with animate(), difference with print.gganim() and knit_print.gganim()??")
#?play_tour_path
dat_std <- scale_sd(flea[, 1:6])
clas <- flea$species
bas <- basis_pca(dat_std)

## Not run:
## Tour history from tourr::save_history
g_path <- tourr::save_history(dat_std, tour_path = tourr::grand_tour(), max = 3)

## recreate play_tour_path(render_gganimate)
gg <- play_tour_path(tour_path = g_path,  data = dat_std, render_type = render_)
fps = 8L;rewind = FALSE;start_pause = 0.5;end_pause = 1L;
gif_filename = NULL;gif_path = NULL;gganimate_args = list();
gga <- gg + gganimate::transition_states(frame, transition_length = 0L)
class(gga)
?gganimate:::print.gganim

# gganimate::animate(gga, fps = fps, 
#                    rewind = rewind, start_pause = fps * start_pause, 
#                    end_pause = fps * end_pause, #device = 'png'
#                    device = "pdf"
#)


# # gganimate::animate(anim)
```